// SPDX-License-Identifier: Apache-2.0
package hpdcache_uvm_components_pkg;
  import uvm_pkg::*;
  import hpdcache_pkg::*;
  import `HPDCACHE_CONFIG_PKG::*;
  import hpdcache_cva6_types_pkg::*;
  import clock_driver_pkg::*;
  import reset_driver_pkg::*;
  import memory_rsp_model_pkg::*;
  import axi2mem_pkg::*;
  `include "uvm_macros.svh"

  `include "hpdcache_pma_config.svh"
  `include "hpdcache_cri_agent_config.svh"
  `include "hpdcache_env_config.svh"
  `include "hpdcache_cri_item.svh"
  `include "hpdcache_cmi_item.svh"
  `include "hpdcache_cri_sequencer.svh"
  `include "hpdcache_cri_driver.svh"
  `include "hpdcache_cri_monitor.svh"
  `include "hpdcache_cri_agent.svh"
  `include "scoreboard/hpdcache_reference_model.svh"
  `include "scoreboard/hpdcache_predictor.svh"
  `include "scoreboard/hpdcache_cacheable_evaluator.svh"
  `include "scoreboard/hpdcache_uc_amo_forwarding_evaluator.svh"
  `include "scoreboard/hpdcache_scoreboard.svh"
  `include "hpdcache_cmi_monitor.svh"
  `include "hpdcache_cmi_agent.svh"
  `include "hpdcache_clock_driver.svh"
  `include "hpdcache_reset_driver.svh"
  `include "hpdcache_memory_response_model.svh"
  `include "hpdcache_axi2mem.svh"
  `include "hpdcache_env.svh"
  `include "hpdcache_base_seq.svh"
  `include "hpdcache_random_seq_api.svh"
  `include "hpdcache_amo_seq_api.svh"
  `include "hpdcache_random_seq.svh"
  `include "hpdcache_lrsc_seq.svh"
  `include "hpdcache_atomic_seq.svh"
  `include "hpdcache_base_vseq.svh"
  `include "hpdcache_random_vseq.svh"
  `include "hpdcache_atomic_vseq.svh"
  `include "hpdcache_base_test.svh"
  `include "hpdcache_random_test.svh"
  `include "hpdcache_atomic_test.svh"
  `include "hpdcache_on_the_fly_reset_test.svh"
endpackage
